name: shorts_composer
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^0.13.3
  file_picker: ^8.0.3
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1
  url_launcher: ^6.0.12
  google_sign_in: ^6.2.1
  image_picker: ^0.8.4+11
  path_provider: ^2.0.2
  just_audio: ^0.9.18
  audioplayers: 6.1.0 
  ffmpeg_kit_flutter_full_gpl: ^5.1.0
  video_player: ^2.4.2
  permission_handler: ^10.2.0
  gallery_saver: ^2.3.2
  sprintf: ^6.0.0
  open_filex: ^4.2.0
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/response_transcription.json
    - lib/assets/Verdana.ttf